### ISSUE TITLE
Stimpak unable to heal

### ISSUE THREAD

**Issue by Cirvel** [andersmmg/fallout-stuff#1]
When trying to heal with a Stimpak, the item disappears but no health is restored towards the user.
It turns out the Stimpak was not consumed at all since clicking the same slot it was used in the inventory will cause it to reappear back.

**Comment by andersmmg** [comment]
I'll look into this!

**Comment by andersmmg** [comment]
Fixed in [1.7.4](https://github.com/andersmmg/fallout-stuff/releases/tag/v1.7.4)!
