### ISSUE TITLE
serevr crashed and got killed by owo after trying to place a sliding door

### ISSUE THREAD

**Issue by RealxRancor** [andersmmg/fallout-stuff#3]
https://mclo.gs/2PNQN0f#L5

crashlog

**Comment by andersmmg** [comment]
I'll look into it

**Comment by andersmmg** [comment]
Fixed in [1.7.8](https://github.com/andersmmg/fallout-stuff/releases/tag/v1.7.8)

**Comment by RealxRancor** [comment]
testing it rn

**Comment by RealxRancor** [comment]
sry have to sleep now testing it later
